# Generated by Django 4.0.5 on 2022-06-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='modified_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
