# Generated by Django 4.0.5 on 2022-06-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_data_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
