# Generated by Django 4.0.5 on 2022-06-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_rename_id_data_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='ids',
            new_name='id',
        ),
    ]
