apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5123
            name: http
          image: "10.233.61.130:5000/django-test:0.11"