apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django
  labels:
    app: django
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 5123
      name: http
      targetPort: 5123
  type: LoadBalancer