apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: "10.233.61.130:5000/django-test:0.11"
  newName: "python:latest"
  # command: [ "/bin/bash", "-c", "--" ]
  # args: [ "while true; do sleep 30; done;" ]
bases:
- ../../base