apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          imagePullPolicy: Always
          ports:
          - containerPort: 5123
            name: http
#           image: "django-test:0.1"
          image: "python:latest"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django
  labels:
    app: django
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 5123
      name: http
      targetPort: 5123
  type: LoadBalancer
---
